package phase06.generics;

import java.lang.reflect.Method;
import java.util.ArrayList;
import java.util.List;

public class TypeErasure {
    public static void main(String[] args) {
        // 1. Type erasure demonstration
        System.out.println("=== Type Erasure ===");

        List<String> stringList = new ArrayList<>();
        List<Integer> intList = new ArrayList<>();

        // At runtime, both are just ArrayList (type parameters are erased)
        System.out.println("stringList class: " + stringList.getClass());
        System.out.println("intList class: " + intList.getClass());
        System.out.println("Same class? " + stringList.getClass().equals(intList.getClass()));
        System.out.println("Both are ArrayList at runtime (type erased)\n");

        // 2. Bridge methods demonstration via reflection
        System.out.println("=== Bridge Methods ===");

        Parent<String> parent = new Child();
        parent.setValue("Hello");

        // Show bridge method
        for (Method m : Child.class.getMethods()) {
            if (m.getName().equals("setValue") || m.getName().equals("getValue")) {
                System.out.println("Method: " + m + "  [Bridge: " + m.isBridge() + "]");
            }
        }
        System.out.println();

        // 3. Raw types warning (demonstration with @SuppressWarnings)
        System.out.println("=== Raw Types ===");
        rawTypeDemo();

        // 4. Bytecode equivalent demonstration
        System.out.println("\n=== Bytecode Equivalent ===");
        System.out.println("Generic: List<String>  ->  Bytecode equivalent: List (raw)");
        System.out.println("Generic: Box<Integer>  ->  Bytecode equivalent: Box (raw)");
        System.out.println("Type params are replaced with Object (or leftmost bound)");
        System.out.println("Cast instructions are inserted automatically by compiler");

        // Show erased type at bytecode level using reflection
        ErasedType erased = new ErasedType();
        erased.setValue("test");
        System.out.println("\nErasedType getValue return type (after erasure): " +
                getMethodReturnType(ErasedType.class, "getValue"));
    }

    @SuppressWarnings({"rawtypes", "unchecked"})
    private static void rawTypeDemo() {
        System.out.println("Raw type demo:");
        List rawList = new ArrayList(); // raw type - warning suppressed
        rawList.add("String");
        rawList.add(42);

        // Unchecked cast
        List<String> stringList = rawList; // unchecked warning
        System.out.println("Raw list: " + rawList);

        // Runtime danger - ClassCastException only at runtime
        try {
            for (String s : stringList) {
                System.out.println("Item: " + s);
            }
        } catch (ClassCastException e) {
            System.out.println("ClassCastException caught as expected: " + e.getMessage());
        }
    }

    private static String getMethodReturnType(Class<?> clazz, String methodName) {
        for (Method m : clazz.getMethods()) {
            if (m.getName().equals(methodName)) {
                return m.getReturnType().getSimpleName();
            }
        }
        return "not found";
    }
}

// --- Bridge Method Demo ---

class Parent<T> {
    private T value;

    public void setValue(T value) {
        this.value = value;
        System.out.println("Parent.setValue: " + value);
    }

    public T getValue() {
        return value;
    }
}

class Child extends Parent<String> {
    @Override
    public void setValue(String value) {
        System.out.println("Child.setValue: " + value);
    }
    // Bridge method setValue(Object) is automatically generated by compiler
}

// --- Type Erasure Demo ---

class ErasedType<T> {
    private T value;

    public void setValue(T value) {
        this.value = value;
    }

    public T getValue() {
        return value;
    }
    // After erasure: T -> Object, so getValue() returns Object at bytecode level
}
